### ISSUE TITLE
References to Third Party Code

### ISSUE THREAD

**Issue by cybercamphackathon** [CarlosLannister/IHS#7]
Please mention when you have borrowed a piece of code from a third party.
I'm thinking on the "attacks" part, but this also applies to the whole tool.

**Comment by CarlosLannister** [comment]
This was already addressed on the wiki https://github.com/CarlosLannister/IHS/wiki/5.-Wanting-to-contribute-!!!

But to make clear the original creators and efforts we just added additional information to Readme.md. https://github.com/CarlosLannister/IHS

Industrial Hacking Simulator (IHS) is a repository with ICS scenarios built with minicps. IHS scenarios heavily relay on Minicps. Minicps is the work of Security of Cyber-Physical Systems group, https://github.com/scy-phy. And one of his main maintainers was Daniele Antonioli.

Minicps original repo seems to be abandoned so we are using a fork maintained repo that works with Python3. Check the wiki in you want to contribute
