### ISSUE TITLE
Output Files Not In Gitignore

### ISSUE THREAD

**Issue by cybercamphackathon** [CarlosLannister/IHS#9]
**Describe the bug**
I would say that you have some files here that should be added to the .gitignore file
https://github.com/CarlosLannister/IHS/tree/master/attacks

**To Reproduce**
Just click on the link above.

**Expected behavior**
Make sure that only code is included in the repository.

**Comment by CarlosLannister** [comment]
Added to gitignore:
*.ef 
*.pcap 
*.sqlite 

Attacks scripts usage and info will be documented on https://github.com/CarlosLannister/IHS/wiki/4.-Usefull-commands-to-audit-Industrial-Systems 

Waiting to close the issue until documentation is done
